"""is_worker_field_user_model

Revision ID: 74a2c5fc5abe
Revises: 229438470a3c
Create Date: 2021-12-11 15:29:19.075064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a2c5fc5abe'
down_revision = '229438470a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_worker', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_worker')
    # ### end Alembic commands ###
