"""add_healthcheck_table

Revision ID: f33c05f3c96f
Revises: 74a2c5fc5abe
Create Date: 2021-12-11 20:16:37.468012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33c05f3c96f'
down_revision = '74a2c5fc5abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthstack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=254), server_default=sa.text('NULL'), nullable=True),
    sa.Column('domains', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('delay_between_checks', sa.Integer(), nullable=False),
    sa.Column('emails_list', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], name='worker_id_fk', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthstack_id'), 'healthstack', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthstack_id'), table_name='healthstack')
    op.drop_table('healthstack')
    # ### end Alembic commands ###
